baseURL = "http://example.org/"
languageCode = "en-us"
title = "IEEE Computer Society UTEC"
theme = "ananke"

[params]
  favicon = "/img/favicon.png"
  site_logo = "/img/logo-white.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/ieee.cs.utec/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/ieee-computer-society-utec/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/bg.jpg"
  recent_posts_number = 2
